// Code generated by mockery v2.39.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// NodekitProxyMock is an autogenerated mock type for the NodekitProxyInterface type
type NodekitProxyMock struct {
	mock.Mock
}

// SubmitMsgTx provides a mock function with given fields: ctx, data
func (_m *NodekitProxyMock) SubmitMsgTx(ctx context.Context, data []byte) (string, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for SubmitMsgTx")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) (string, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte) string); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewNodekitProxyMock creates a new instance of NodekitProxyMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNodekitProxyMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *NodekitProxyMock {
	mock := &NodekitProxyMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
